### PR TITLE
Fix PHP7 compatibility issue in line unpacking

### PR DESCRIPTION
**Pull request by mark-101**
Fix issue #9 - usage of list() has changed in PHP 7 so removed it from unpacking code
Also fixed indentation to make code clearer
Fix issue #7 - trim return string to stop undefined offset notice

### CODE REVIEW

**Comment by overint** [comment]
Thanks for the pull! Have you tested your new code with both the sandbox and live endpoints?

**Comment by mark-101** [comment]
Just with the sandbox so far; it should go live in the next week or so.

**Comment by overint** [comment]
Ok, let me know once it's tested and i'll merge it in.

**Comment by mark-101** [comment]
Code is now live and has been tested against the live endpoint without any problems.

**Pull request merged**
